ECommarce_Project/urls.py
from django.contrib import admin
from django.urls import path,include

# Show Media Files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Shop.urls')),
    path('user-account/',include('LoginApp.urls')),
    path('order/',include('Order.urls')),
    path('payment/',include('Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LoginApp/urls.py
from django.urls import path
from LoginApp import views

app_name = "LoginApp"


urlpatterns = [
    path('signup/',views.signUpUser, name='signup'),
    path('login/',views.loginUser, name='login'),
    path('logout/',views.logoutUser, name='logout'),
    path('profile/',views.profile, name='profile'),
    path('change-profile/',views.userProfile, name='changeprofile'),
]

Shop/urls.py
from django.urls import path
from Shop import views

app_name = "Shop"


urlpatterns = [
    # path('',views.test, name='test'),
    path('',views.ProductListView.as_view(), name='home'),
    path('product-detail/<pk>/',views.ProductDetail.as_view(), name='product-detail'),
]

templates/Login/change-profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}{{user.profile.full_name}} | Profile{% endblock title_block %}

{% block body_block %}
<h2>{{user.profile.full_name}} </h2>
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{form|crispy}}
    <button class='btn btn-sm btn-warning' type="submit">Save</button>
</form><br><br>

{% endblock body_block %}

templates/Login/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}Login Account{% endblock title_block %}

{% block body_block %}

<div class="row offset-3" style='padding-top:3rem'>
    <div class="col-8">
        <h2>Login Account: </h2><hr>
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {{form|crispy}}
            <button class='btn btn-success' type="submit">Login Account</button>
        </form><br>
        <span>Don't have an account? <a href="{% url 'LoginApp:signup' %}">Sign up</a></span>
    </div>
</div>
{% endblock body_block %}

templates/Login/profile.html
{% extends "base.html" %}
{% block title_block %}{{user.profile.full_name}} | Profile{% endblock title_block %}

{% block body_block %}
<h2>{{userprofile.full_name}} </h2>

<p>City: {{userprofile.city}}</p>
<p>Address: {{userprofile.address_1}}</p>

<a href="{% url 'LoginApp:changeprofile' %}">Edit Profile</a>
{% endblock body_block %}

templates/Login/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}Create New Account{% endblock title_block %}

{% block body_block %}
<div class="row offset-3" style='padding-top:3rem;'>
    <div class="col-8">
        <h2>Create new acconut: </h2>
        <form action="" method="post" novalidate>
            {% csrf_token %}
           
            {{form|crispy }}
       
            <button class='btn btn-success' type="submit">Create Account</button>
        </form><br>
        <p>Already have an account? <a href="{% url 'LoginApp:login' %}">Login</a></p>
    </div>
</div>

{% endblock body_block %}