ECommarce_Project/urls.py
from django.contrib import admin
from django.urls import path,include

# Show Media Files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Shop.urls')),
    path('user-account/',include('LoginApp.urls')),
    path('order/',include('Order.urls')),
    path('payment/',include('Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Order/urls.py
from django.urls import path
from Order import views

app_name = "Order"

urlpatterns = [
    path('add/<pk>/', views.addToCart,name='add'),
    path('cart/',views.cartView, name='cart'),
    path('remove/<pk>',views.removeItemCart, name='remove'),
    path('increase/<pk>',views.increaseCartItem, name='increase'),
    path('decrease/<pk>',views.decreaseCartItem, name='decrease'),
]

Shop/urls.py
from django.urls import path
from Shop import views

app_name = "Shop"


urlpatterns = [
    # path('',views.test, name='test'),
    path('',views.ProductListView.as_view(), name='home'),
    path('product-detail/<pk>/',views.ProductDetail.as_view(), name='product-detail'),
]

Shop/models.py
from django.db import models


#models
class Category(models.Model):
    title = models.CharField(max_length=20)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"

class Product(models.Model):
    mainImage = models.ImageField(upload_to="Products")
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
    preview_text = models.TextField(max_length=200, verbose_name='PreviewText')
    details = models.TextField(max_length=1000, verbose_name="Description")
    price = models.FloatField()
    old_price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)
    # slug = models.SlugField()


    def __str__(self):
        return self.name
    class Meta:
        ordering = ['-created']

Shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import DetailView, ListView
from Shop.models import Product
# Create views here.
# def test(request):
#     return render(request, 'shop/index.html')

class ProductListView(ListView):
    model = Product
    template_name = "Shop/home.html"


from django.contrib.auth.mixins import LoginRequiredMixin
class ProductDetail(DetailView,LoginRequiredMixin):
    model = Product
    template_name = 'Shop/product_detail.html'
    context_object_name = 'productdetail'

templates/Shop/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}Mini-Shop{% endblock title_block %}

{% block body_block %}


<div class="container">
    {% comment %} <div class="class"> {% endcomment %}
        <h2 class="my-1">Featured Products</h2><hr>
        <div class="row">
            {% for product in object_list %}
            <div class="col-md-6 col-sm-12 col-lg-3">
                <figure class="card card-product">
                    <div class="img-wrap">
                        <a href="{% url 'Shop:product-detail' pk=product.pk %}" >
                            <img src="/media/{{product.mainImage}}" alt="" srcset="" style="width: 100%;height:300px;">
                        </a>
                    </div>
                    <figcaption class="info-wrap">
                        <h6 class="title"><a href="{% url 'Shop:product-detail' pk=product.pk %}" >{{product.name}}</a></h6>
                        <div class="action-wrap">
                            <div class="price-wrap h5">
                                <span class="price-new">Price: &#2547;{{product.price|floatformat:2}}</span>
                                <span class="price-old">&#2547;<strike>{{product.old_price|floatformat:2}}</strike></span>
                            </div>
                        </div>
                        
                    </figcaption>
                </figure>
            </div>
            {% endfor %}
        </div>
    
    {% comment %} </div> {% endcomment %}
</div>

{% endblock body_block %}

templates/Shop/product_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container">
    <div class="card">
        <div class="row">
            <aside class="col-sm-12 col-md-5 col-lg-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div class="">
                            <a href="#"><img src="/media/{{productdetail.mainImage}}" style="width:450px" alt=""></a>
                        </div>
                    </div>
                </article>
            </aside>
            <aside class="col-sm-12 col-lg-7 col-md-7">
                <article class="card-body p-5">
                    <h3 class="title mp-3">{{productdetail.name|title}}</h3>
                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">BDT &#2547;</span><span class="num">{{productdetail.price|floatformat:2}}</span>
                            <strike style="color:
                            #7e7e7e" class="num">&#2547;{{productdetail.old_price|floatformat:2}}</strike>
                        </span>
                    </p>
                    <dl class="item-property">
                        <dt>Description</dt>
                        <dd>
                            <p>{{productdetail.details}}</p>
                        </dd>
                    </dl>
                    <a href="{% url 'Order:add' pk=productdetail.pk %}" class="btn btn-lg my-2 btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i>Add to Cart</a>
                </article>
            </aside>
        </div>
    </div>
</div>

{% endblock body_block %}