ECommarce_Project/urls.py
from django.contrib import admin
from django.urls import path,include

# Show Media Files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Shop.urls')),
    path('user-account/',include('LoginApp.urls')),
    path('order/',include('Order.urls')),
    path('payment/',include('Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LoginApp/urls.py
from django.urls import path
from LoginApp import views

app_name = "LoginApp"


urlpatterns = [
    path('signup/',views.signUpUser, name='signup'),
    path('login/',views.loginUser, name='login'),
    path('logout/',views.logoutUser, name='logout'),
    path('profile/',views.profile, name='profile'),
    path('change-profile/',views.userProfile, name='changeprofile'),
]

Order/urls.py
from django.urls import path
from Order import views

app_name = "Order"

urlpatterns = [
    path('add/<pk>/', views.addToCart,name='add'),
    path('cart/',views.cartView, name='cart'),
    path('remove/<pk>',views.removeItemCart, name='remove'),
    path('increase/<pk>',views.increaseCartItem, name='increase'),
    path('decrease/<pk>',views.decreaseCartItem, name='decrease'),
]

Payment/urls.py
from django.urls import path
from Payment import views
app_name = "Payment"

urlpatterns = [
    path('checkout/',views.checkOut, name='checkout'),
    path('pay/',views.payment, name='pay'),
    path('status/',views.complete, name='complete'),
    path('purchased/<val_id>/<tran_id>/',views.purchased,name='purchase'),
    path('orders/', views.orderView, name='orders'),
]

Shop/urls.py
from django.urls import path
from Shop import views

app_name = "Shop"


urlpatterns = [
    # path('',views.test, name='test'),
    path('',views.ProductListView.as_view(), name='home'),
    path('product-detail/<pk>/',views.ProductDetail.as_view(), name='product-detail'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title_block %}{% endblock title_block %}</title>
   
    <style>
        body{
            background-color: #f0f2f5;
        }
        .card{
            height: 350px;
        }
        .card-product::after{
            content:"";
            display: table;
            clear: both;
            visibility: hidden;
        }
        .card-product .price-new, .card-product .price{
            margin-right: 5px;

        }
        .card-product .price-old{
            color: #999;
        }
        .card-product .img-wrap{
            border-radius: 3px 3px 0 0;
            overflow: hidden;
            position: relative;
            height: 100%;
            text-align: center;

        }
        .card-product .img-wrap{
            max-height:100%;
            max-width: 100%;
            object-fit: cover;
        }
        .card-product .info-wrap{
            overflow: hidden;
            padding: 15px;
            border-top: 1px solid #eee;
        }
        .card-product .action-wrap{
            padding-top: 4px;
            margin-top: 4px;
        }
        .card-product .bottom-wrap{
            padding: 15px;
            border-top: 1px solid #eee;

        }
        .card-product .title{
            margin-top: 0px;

        }
        
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        {% block message_block %}
        <div class="row offset-4" style="margin-top:1rem">
            <div class="col-6">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        {% endblock message_block %}
        
        {% block body_block %}{% endblock body_block %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class='navbar-brand text-danger font-weight-bold' href="{% url 'Shop:home' %}">Mini-Shop</a>
      <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNav' aria-controls='navbarNav' aria-expanded='false' aria-label='Toggle navigation'>
          <span class='navbar-toggler-icon'></span>
      </button>
      <div class='collapse navbar-collapse' id='navbarNav'>
          <ul class='navbar-nav ml-auto'>
            {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'Order:cart' %}" class="nav-link"><i style="color:blue" class="fa fa-shopping-cart"></i>Cart <span class="text-danger font-weight-bold">{{request.user|cartTotal }}</span></a>
        </li>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">@{{request.user.profile.username}}</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'LoginApp:profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'Payment:orders' %}">Orders</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'LoginApp:logout' %}">Logout</a>
          </div>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'LoginApp:login' %}">Login</a>
        </li>
        {% endif %}
        
      </ul>
      <!-- <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
    </div>
    </div>

  </nav>