ECommarce_Project/urls.py
from django.contrib import admin
from django.urls import path,include

# Show Media Files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Shop.urls')),
    path('user-account/',include('LoginApp.urls')),
    path('order/',include('Order.urls')),
    path('payment/',include('Payment.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Order/urls.py
from django.urls import path
from Order import views

app_name = "Order"

urlpatterns = [
    path('add/<pk>/', views.addToCart,name='add'),
    path('cart/',views.cartView, name='cart'),
    path('remove/<pk>',views.removeItemCart, name='remove'),
    path('increase/<pk>',views.increaseCartItem, name='increase'),
    path('decrease/<pk>',views.decreaseCartItem, name='decrease'),
]

Payment/urls.py
from django.urls import path
from Payment import views
app_name = "Payment"

urlpatterns = [
    path('checkout/',views.checkOut, name='checkout'),
    path('pay/',views.payment, name='pay'),
    path('status/',views.complete, name='complete'),
    path('purchased/<val_id>/<tran_id>/',views.purchased,name='purchase'),
    path('orders/', views.orderView, name='orders'),
]

Shop/urls.py
from django.urls import path
from Shop import views

app_name = "Shop"


urlpatterns = [
    # path('',views.test, name='test'),
    path('',views.ProductListView.as_view(), name='home'),
    path('product-detail/<pk>/',views.ProductDetail.as_view(), name='product-detail'),
]

Order/models.py
from django.db import models
from django.conf import settings
from Shop.models import Product
# Create your models here.
class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cart")
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (f'{self.quantity} X {self.item}')
    
    def getTotal(self):
        total = self.item.price * self.quantity
        floatTotal = format(total, '0.2f')
        return floatTotal


class Order(models.Model):
    orderitems = models.ManyToManyField(Cart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    paymentId = models.CharField(max_length=264, blank=True,null=True)
    orderId = models.CharField(max_length=200,blank=True,null=True)

    def getTotals(self):
        total = 0
        for orderItem in self.orderitems.all():
            total += float(orderItem.getTotal())
        # return 
        return format(total, '0.2f')
    
    def __str__(self):
        return (f'Order Item-{self.orderitems.count()} | {self.user.email}')
    

Order/views.py
from django.shortcuts import render,get_object_or_404, redirect

# Authentication
from django.contrib.auth.decorators import login_required

# Models
from Order.models import Cart,Order
from Shop.models import Product
# Messages
from django.contrib import messages
# Create your views here.

@login_required
def addToCart(request, pk):
    item = get_object_or_404(Product, pk=pk)
    # print("Item")
    # print(item)
    order_item = Cart.objects.get_or_create(item=item, user=request.user, purchased=False)
    # print("Order Item Object:")
    # print(order_item)
    # print(order_item[0])
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    # print("Order Qs:")
    # print(order_qs)
    #print(order_qs[0])
    if order_qs.exists():
        order = order_qs[0]
        # print("If Order exist")
        # print(order)
        if order.orderitems.filter(item=item).exists():
            order_item[0].quantity += 1
            order_item[0].save()
            messages.info(request, "This item quantity was updated.")
            return redirect("Shop:home")
        else:
            order.orderitems.add(order_item[0])
            messages.info(request, "This item was added to your cart.")
            return redirect("Shop:home")
    else:
        order = Order(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        messages.info(request, "This item was added to your cart.")
        return redirect("Shop:home")

@login_required
def cartView(request):
    carts = Cart.objects.filter(user=request.user,purchased=False)
    orders = Order.objects.filter(user=request.user, ordered = False)
    if carts.exists() and orders.exists():
        order = orders[0]
        return render(request, 'Order/cart.html', context={'carts':carts, 'order':order})
    else:
        messages.warning(request,"You don't have any item in your cart!")
        return redirect("Shop:home")
    
@login_required
def removeItemCart(request,pk):
    item = get_object_or_404(Product,pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item, user=request.user,purchased=False)[0]
            # order_item = order_item[0]
            order.orderitems.remove(order_item)
            order_item.delete()
            messages.info(request,"This item was remove  your cart!")
            return redirect("Order:cart")
        else:
            messages.info(request,"This item was not in your cart!")
            return redirect("Shop:home")
    else:
        messages.info(request,"You don't have an active item!")
        return redirect("Shop:home")


@login_required
def increaseCartItem(request,pk):
    item = get_object_or_404(Product,pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item,user=request.user,purchased=False)[0]
            if order_item.quantity >= 1:
                order_item.quantity += 1
                order_item.save()
                return redirect("Order:cart")
        else:
            messages.warning(request,f"{item.name} is not in your cart!")
            return redirect("Order:cart")
    else:
        messages.info(request,"You don't have an active order!")
        return redirect("Shop:home")


@login_required
def decreaseCartItem(request,pk):
    item = get_object_or_404(Product,pk=pk)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.orderitems.filter(item=item).exists():
            order_item = Cart.objects.filter(item=item,user=request.user,purchased=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                return redirect("Order:cart")
            else:
                return redirect("Order:cart")
        else:
            messages.warning(request,f"{item.name} is not in your cart!")
            return redirect("Order:cart")
    else:
        messages.info(request,"You don't have an active order!")
        return redirect("Shop:home")

templates/Order/cart.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container">
    <div class="checkout-area">
    <!-- <div class="my-5"> -->
        <h2>Your Cart</h2>
    <!-- </div> -->
    <table class="table table-hover">
        <thead>
            <tr class="bgtrhd">
                <th scope="col" width="5%">#</th>
                <th scope="col">Product Name</th>
                <th scope="col">Quantity</th>
                <th scope="col" style="text-align: right;">Price</th>
                <th scope="col" style="text-align: right;">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for cart in carts %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ cart.item.name|title }} ({{cart.item.category.title}})</td>
                <!-- <td scope="row">{{ cart.quantity }}</td> -->
                <td>
                    <a class="mr-2" href="{% url 'Order:decrease' pk=cart.item.pk %}"><span class="badge badge-light"><i class="fas fa-minus"></i></span></a>
                    {{ cart.quantity }}
                    <a class="mr-2" href="{% url 'Order:increase' pk=cart.item.pk %}"><span class="badge badge-light"><i class="fas fa-plus"></i></span></a>
                </td>
                <td style="text-align: right;">&#2547 {{ cart.getTotal  }}</td>
                <td style="text-align: right;"><a href="{% url 'Order:remove' pk=cart.item.pk %}" class="btn btn-danger btn-sm">Remove</a></td>
            </tr>
            {% endfor %}
            <tr class="bdtr">
                <th scope="row"></th>
                <td colspan="2">Total</td>
                <td style="text-align: right;">&#2547 {{order.getTotals }}</td>
                <td></td>
            </tr>
        </tbody>
    </table>
    <div class="row  offset-md-7">
        <a href="{% url 'Shop:home' %}" class="btn btn-warning mr-4">Continue Shopping</a>
        <a href="{% url 'Payment:checkout' %}" class="btn btn-success">Proceed To Checkout</a>
    </div>
</div>
</div><br><br>


{% endblock body_block %}